---

- name: Pinging leader ucp-primary and check if it's up and running
  uri:
    url: "https://{{ hostvars[groups['ucp-primary-leader'][0]]['ansible_eth0']['ipv4']['address'] }}/_ping"
    validate_certs: no
  register: ucp_primary
  until: ucp_primary.status == 200
  retries: 50
  delay: 2

- name: Joining Workers to UCP Cluster
  command: docker swarm join --token {{ hostvars[groups['ucp-primary-leader'][0]]['worker_token'].stdout }} {{ hostvars[groups['ucp-primary-leader'][0]]['ansible_eth0']['ipv4']['address'] }}

