---
- hosts: all
  become: yes
  roles:
    - docker-engine

- hosts: ucp-primary-leader
  become: yes
  roles:
    - docker-ucp-primary

- hosts: ucp-replica-managers
  become: yes
  serial: 1 # need to join one by one only
  roles:
    - docker-ucp-replica

- hosts: ucp-worker
  become: yes
  roles:
    - docker-ucp-worker
